### PR TITLE
Zenith Tomes bug.yml

### PR DESCRIPTION
**Pull request by Wiktolego**
Zenith Tomes are still bugged

### CODE REVIEW

**Comment by Rizzomatt** [comment]
Hey guys, does anybody had problems with Fallen Icon quest? I killed the guy and yet the quest is not completed
Maybe there's a way to set the quest as finished with some line

**Comment by SoraNoGinga** [comment]
I'm having an error in the middle of the screen when playing, sometimes a black rectangle appears that obstructs the view.

Captura de pantalla 2024-05-03 162857

**Comment by Loby1520** [comment]
image
My power level doesn't improve despite having netherite diamond armor!

**Comment by Xig2008** [comment]
my power level is bugged because i have an a diamond legendary armor and i don't see my power pls fix the bug

**Comment by Nick-77ab2** [comment]
Since there's no issues section: There's a crafting recipe overlap, can't build builders wands because they craft spears instead.

**Pull request closed without merging**
