### PR TITLE
[Issue]: Modpack closes with error 6 on linux

### PR DESCRIPTION
**Pull request by marvin1099**
Since issues are disabled I'm just going to use this pull request.
When i try to start "Prominence II RPG" on my linux box, 
the following error log gets printed 
(btw. i have tested v2.8.6 and v2.8.7 same results):

https://mclo.gs/WQ3dbCG

Any help is wellcome

### CODE REVIEW

**Comment by Shadowgave** [comment]
sometime it will not let me login out of the sever so i can get off and go to bed

**Comment by HugKitten** [comment]
Same issue

**Comment by Pencilsoup** [comment]
Ancient Debris and Diamond Ore unable to be put into data card encoder for Industrial Revolution

**Comment by marvin1099** [comment]
> I was able to fix it by installing gflw and then add the -Dorg.lwjgl.glfw.libname=/usr/lib64/libglfw.so flag to the java arguments.

Thanks, this works, 
to be exact i can enable this in prism launcher under tweaks.
That works nicely.
OnepeAl is also on since some other modpack seemed to need it
image

**Pull request closed without merging**
